create DATABASE INVENTARIO;
USE INVENTARIO;

CREATE TABLE APP_CATEGORIAS(
ID_APP_CATEGORIA					INT NOT NULL AUTO_INCREMENT,
NOMBRE								VARCHAR(50),
ESTADO								VARCHAR(25),
PRIMARY KEY (ID_APP_CATEGORIA)			
);


CREATE TABLE APP_BIENES(
ID_APP_BIEN						INT NOT NULL AUTO_INCREMENT,
DESCRIPCION						VARCHAR(150),
CATEGORIA_ID					INT,
ESTADO							VARCHAR(25),

PRIMARY KEY (ID_APP_BIEN),
FOREIGN KEY (CATEGORIA_ID)
REFERENCES APP_CATEGORIAS(ID_APP_CATEGORIA)
);

